apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1UQXhPVEE0TWpFME1sb1hEVE15TVRBeE5qQTRNakUwTWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS0crCkpCN1NuZkFOQ2VmMlJmTC9SWk5FT3pLMk1vSUNDSlQrZmxzc1ZxQUM5SCtJSUFSM1NsVzIzanJLaU5rK1JNS0IKM0N2WGJOTFhNNTR5RHRFSHZPaU92RDJFdTR5UlBOSkN1cE5jYko5S2gwVkM4VVp5Z2orQXlmMU94TG9mc0UzUwpwR3R6S053aEorN0FTVmI0bmNhSDZBSFdmd2dQQktFMmYzcEF4VDFsODE0UVVEL3JwVjVPbTA1SjcyRWViZmo2CnRWR2tzd0NNSklDc0IzZjF2T1gzancySGM4RGxoekwyaEFaNnY4c3ZmL1F5UHozOEhEc015ZFNRRkh4WVJnenAKU1doanFaWTdUcDJDSWU0cW9CU29ZSGNtWFNwY3JrelVka3FucUVpQTJBdXQzL01kOTJuU0N3RUxmS1NZaUVHUQpDcXFXc015QUhpNEZLUVlTdmwwQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJblQ2RWFqajFTWkRyVVp0L0dqK0dyUkV4eHRNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSFhsV1lzTCtMYlZCbjJaY0dTMwp0R3dYZmNQZEwwV2tMd3h1RXV1QW9HR0FTNWhqR08zMDZwRkhBOFpiUGhQYkM0VDYxZml3dGs1dUxXVmM4Y1h6Cm9BS20xN0RmbnFWTHdDMENZeUtJR05qUkNKZ2lVVVJ1L2VOazVYMk5KNkZuekEzSmVhSERKUU9qL3BXSTJDdDUKY3U0dCtPbzhGcHBWQlpIcWhsTjBXbjM2QXhVckJEdUR3ZjhWaUxiUEV0SVRaVzgvakJkTkIzdE1Mak8zS0J3SgpNVDhSaHZsWDhXRWZMNGRaT3VYRGFTbmJ3anZ5aFlleHVIZkJIZ21HUWFudG5LeXEvQlBwT3U1UGs2Ui9SRVlZCm5ULzJySE1MQzI2U29VYmhIeDlGUm9RTXk0Q2ExUkxpSEdTeU5BaC9ib3Q0aG9HUWN5WWRrNUM2UnhhRXl0d0EKanRVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://pandora.intel.com:8443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJRXFrOW9RN3Rtc0V3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TWpFd01Ua3dPREl4TkRKYUZ3MHlNekV3TVRrd09ESXhORGhhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXg0dzJEdjNTR1BXejdZMnkKQkpkclVkWEdLQnlvYjdlR0dNQnVDOEpabnU2L0RMYWZJNGY5eU5GV2FCenpkWGRVWHJUNlB5SmxiaW5rclBNcApJWTJlOEF5c09GYWxXNHdFSzlmcDU2V2lPd0s2UlJGbjR6eUFHVnJHVnp6Z1JZc0xUZHBseGVKRG9NWU9hN1h1CktmMy9HRXlHam9Kbmpubmpkc3hPT3ROQ1RyNHRWTmE0ZlgzUU1WdEpzaHp4MTd4dnFacnpJT3BXbUNGVEZRMDcKWWFuYUFXYUdYM2NVQWFyamZJeEpuNzR0U2ozYjdVYlFEanYvMW91NUs5QkpCZmNIVlllY0NXWW54Z3U5c0ZKQQpBNmJMQXNLT0t3aTRqMEpKOVlQYmhkZ0ZKZG5Wd3hVcmhoY3h3UkJHenFXaUw2TW9KTGM3TXFxZWtOZ1NkTFB4CmY0Zjhqd0lEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JTSjAraEdvNDlVbVE2MUdiZnhvL2hxMFJNYwpiVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBUkVidENqLzQwTEsxRlBrOElUSUI3UHZhME1wdkJGZ0pJeXNYCjBFMDgxUjMxVkdRa3BrS1laVFliSHhVN2x2ZkpraUZZUlRJVlI2RlBIZFRqSVYwME8rVU9VVWNEZEJFVDZCQW0KYmwyRTJtZFVGRkhpSyt4T1k2SjZLNHB6OTcwd0hydFMySDh5RmpsQkVOcUpqTUt6SEkzLzhBZFBCcnk2YkNLQgpNVVIyZXBtcE4xbUpOa2dadFNZN3V5bWpwMFdGakNZeGV1NUwvSXg1UW0wTHNubk00d05jSnQ3OXd5MXdiMGl2CnNmQjlGMERMVHNnNE5XM2toL3RMN3JraEtRcEdRaXpVQlI2TXlUd1NrZEExN3lsTU12SUZkRlA0UENQbE9TWUEKOUtpRE1MbTdjZzRkNit2blZQT245Q0k0VzlnSE9VMW5DVlZiSXQ0L1FqWW1QRmI3Rmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeDR3MkR2M1NHUFd6N1kyeUJKZHJVZFhHS0J5b2I3ZUdHTUJ1QzhKWm51Ni9ETGFmCkk0Zjl5TkZXYUJ6emRYZFVYclQ2UHlKbGJpbmtyUE1wSVkyZThBeXNPRmFsVzR3RUs5ZnA1NldpT3dLNlJSRm4KNHp5QUdWckdWenpnUllzTFRkcGx4ZUpEb01ZT2E3WHVLZjMvR0V5R2pvSm5qbm5qZHN4T090TkNUcjR0Vk5hNApmWDNRTVZ0SnNoengxN3h2cVpyeklPcFdtQ0ZURlEwN1lhbmFBV2FHWDNjVUFhcmpmSXhKbjc0dFNqM2I3VWJRCkRqdi8xb3U1SzlCSkJmY0hWWWVjQ1dZbnhndTlzRkpBQTZiTEFzS09Ld2k0ajBKSjlZUGJoZGdGSmRuVnd4VXIKaGhjeHdSQkd6cVdpTDZNb0pMYzdNcXFla05nU2RMUHhmNGY4andJREFRQUJBb0lCQUFtWTVNQ3oxSGIrMmppQwpxQjB3YXlqMGJ5TmV2WHNpQ0lFSVFFS3doajd1bktHdjV0ZCtvdVlWcTJJMmdqOFVEaXEvNllrL3prRU9Jc0Z1CnNIdThvL2hIbzhEUjZnSU5LZVl4N0Q0SDZWV05QQWcyWGhpL3dDbDRCRElONjN0c3hJNXFBcHNSMXM3VXQ3elcKY3kzeDJXTUJ5emJ2YnF1YmtTVVZqbTJsMjNxTjlUWTNyUUxoZ1NGdU9ycTJRY09Kc2xjZWxyeDhoMWpnWTFSeAovSmEzWlliRUM2RnhMd3g5RGN1WGNxYkxIalN6MWFhbmEzckNpeEdoazhMT2x0bG8yY0pwZnVmK2t6Q3hycXRTClk5MkZmcmlLdCtkOHNjQVFoOWlFbndBMW15aUxNTlBRK004OEpucGNPVWxUK21iN2JIYnRuZ3B4N1RlV29yR04KOWpEV3BnRUNnWUVBOFloa0dyQ3FnQUVJZlM2TTl4SVlDTkZCVVVlMXRCeEd1ZnRveTkxN2RteTJ3elQwN0JuawpRemtBcEdEWk1CSVVEOHo5U2s0eE1IZUordzhsbjMrUXIxMzZGLzN2VWtKWXFPUDBuUWlxa3A3S2Fna3VpbVloCmg5YzU5WkVDMkY3NVZQcDVtVTFySFdTNkpxK2RXOWZKeEZiTDM3WlAwUHY0TjBlYjl4dUQzWkVDZ1lFQTA0QUgKeTdsMEg5NkI1SHBpeUppSFZlS3JyS1QxOHAwRE1MK0xxVWxoWDlUaVAzaThsOW5NU2N1US9IUmExai9MWkoxRwp3QXpmZEJGUFJqUGQyNDQ0bXFBNDhSVEQ1U3J3Tllkb0dUM01jYnBFeG1QQXZWNDR6bURaaUFBbmEwMkNMYkplCnhPS0F1M2RvQmE0eTJ1VUZTdXhKMFJXeWk5V0pRU3U5cng0WnFCOENnWUVBbXJmd3ovd05LL1A5ZVJyaHA3OEsKY0ZPREVNcnJ4VlU3cFJVOEd5TmtYQWJseUFQYlJJYU5adFpUNS9nMkNBbjhtZWFJOWhsQ2Z6YUR4N1A3T01HaApjQVMyR0xwTW5KZnRiVHFnemhyb0VRWHd5WjNhRjBPM0JPcEVzVjVUd1VDTlhQY1ovNjdOQjhZblRITEFUVDNjCmZJM1JDUndpNHM4VlFHdjVwNEFUcDFFQ2dZQm1wTllqdXdkdWlCQkdFRmRzdndtL1Z0aTJXd0M2RkJWK1RSZTgKdXM0MU1oM3phK2NyVXhwZ0hobHBUQmJocitoSUZrUkY1SGwxM1FpNksyWGFyalV1WmQvOHNIVTUvUkxEQjhvdgpwZHhZdld1dlZLNHZ1VkNjYUVocVJwamE3S3ptL0pBZHdVZDBzOGlhS1NhcE1ValdTY0t4WkhSWWhQT3QyMHFkCmVHQS9SUUtCZ0VaZ2ZmajkvVjZ3YndkelMrN2huZDlQUmdYTytOb0VPWU02WmdCR1JNems5cEFZZTZOcGpFNjAKNnVTeDBHZUttQUtrSy9rZjMwMytFUWVpYjl3d2NEbElUV2dGYS9vS3JaVjZqb01PWnhwMW8yYVlXSURmR0tFRQpvd05aRGthUWtDV3R6T0FRbDhYditxYTZyRWQ5bCtubWwvRkNrM1JKU0hTejErd2g1enR4Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

templates:
  deployment: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: $name
    spec:
      selector:
        matchLabels:
          app: $app
      template:
        metadata:
          labels:
            app: $app
        spec:
          containers:
          - name: $container_name
            image: $container_image
            ports:
              - containerPort: $port
            imagePullPolicy: IfNotPresent
          nodeName: td-guest

  service: |
    apiVersion: v1
    kind: Service
    metadata:
      name: $name
    spec:
      ports:
      - port: $port
        protocol: TCP
      selector:
        app: $app
      type: NodePort

  job: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: $name
    spec:
      template:
        spec:
          containers:
          - name: $container_name
            image: $container_image
            command: $cmd
            args: $args
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
          nodeName: td-guest
      backoffLimit: 0
